---
language: node_js
node_js:
  - "7"

sudo: false
dist: trusty

addons:
  chrome: stable

cache:
  directories:
    - $HOME/.npm
    - node_modules

env:
  global:
    # See https://git.io/vdao3 for details.
    - JOBS=1

before_install:
  - npm config set spin false

script:
  - npm install
  - ember build
  - npm run lint:js
  - npm test

deploy:
  edge:
    branch: v1.8.47
  local_dir: dist/
  provider: pages
  skip_cleanup: true
  repo: burg-kapellendorf/burg-kapellendorf.github.io
  target_branch: master
  github_token: "$GITHUB_TOKEN"
  on:
    branch: master
